"""init

Revision ID: 3445f12d19dc
Revises: bad47196c26a
Create Date: 2026-03-22 22:43:13.453081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3445f12d19dc'
down_revision = 'bad47196c26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_transaction', schema=None) as batch_op:
        batch_op.drop_column('paypal_email')

    # ### end Alembic commands ###
