"""Add withdrawal fields to affiliate_transaction

Revision ID: 3ac31d199384
Revises: 7840a3e74abc
Create Date: 2026-03-05 12:42:08.266808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac31d199384'
down_revision = '7840a3e74abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdraw_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mpesa_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('paybill', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_no', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_transaction', schema=None) as batch_op:
        batch_op.drop_column('account_no')
        batch_op.drop_column('paybill')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('mpesa_phone')
        batch_op.drop_column('withdraw_method')

    # ### end Alembic commands ###
