"""update db

Revision ID: 4534c6c7703a
Revises: 506a9d5d01ff
Create Date: 2026-03-18 17:40:24.774320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4534c6c7703a'
down_revision = '506a9d5d01ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('invitation_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['invitation_code'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('invitation_code')
        batch_op.drop_column('country')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
