"""new logic

Revision ID: 506a9d5d01ff
Revises: dfaa0249e9e9
Create Date: 2026-03-17 00:07:42.882335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506a9d5d01ff'
down_revision = 'dfaa0249e9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('cooldown', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_view')
    op.drop_table('ad_settings')
    # ### end Alembic commands ###
