"""timewalltransaction

Revision ID: 66f05e06a26a
Revises: ca99b49e4796
Create Date: 2026-03-26 15:49:33.163476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f05e06a26a'
down_revision = 'ca99b49e4796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timewall_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('currency_amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timewall_transaction')
    # ### end Alembic commands ###
